openapi: 3.0.0
info:
  title: XScopeHub ETL API
  version: 0.1.0
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: metrics
